library/Search/Google.php

I haven't tested this except that it removes a bunch of PHP notices.

Fix incorrect property

---

library/Search/Google.php

GCS JSON API returns up to the first 100 results only, see https://developers.google.com/custom-search/json-api/v1/using_rest#search_request_metadata:
"Note: This API returns up to the first 100 results only."
This seems correct in my testing.
It's a bit confusing since the XML API seems to return 1000 results. Are you using the XML-API on helsingborg.se? There you have more than 100 results, e.g http://www.helsingborg.se/?s=dokument&index=261. Clicking page 28 and 29 shows strange behaviour though, but it might be another bug.
Since it's maximum 10 pages I could simplify the pager logic a bit by always showing 1-N

Fix pager showing more than 10 pages

---

views/templates/master.blade.php

Fixes incorrect date format for meta data.
https://developers.google.com/custom-search/docs/structured_data

Change meta pubdate and moddate to ISO 8601 format

---

library/Admin/Customizer.php

I get a notice when logged in as a special user. Not sure why but this removes the notice.

Fix notice

---

library/Helper/NavigationTree.php

Fix logic for hidden top level menu items

---

library/Admin/UI/Editor.php

Fixes fatal error when setting STYLEGUIDE_VERSION constant

Fix incorrect call to getStyleguideTheme()

---

assets/dist/js/mce-picons.php
library/Admin/TinyMce/MceButtons/MceButtons.php
library/Admin/UI/Editor.php
library/Helper/Styleguide.php
library/Theme/Enqueue.php
readme.md

Allows setting the styleguide URI via the already existing `MUNICIPIO_STYLEGUIDE_URI` define.

Make styleguide URI configurable

---

assets/source/3.0/js/fab.js
assets/source/3.0/js/municipio.js
views/v3/templates/master.blade.php

Add FAB that is revealed by scrolling and scroll
window y to top 0 when clicked.

To the top fab

---

assets/source/3.0/sass/generic.scss
assets/source/3.0/sass/main.scss
assets/source/3.0/sass/search.scss
library/Controller/Search.php
views/v3/partials/search/result-item.blade.php
views/v3/partials/search/wp.blade.php

Add method that prepares an array of result data.
Add method that prepares an array of pagination data.
Add search result item partial.
Add minor css tweaking.

Search result

---

assets/source/3.0/sass/article.scss
assets/source/3.0/sass/generic.scss
assets/source/3.0/sass/main.scss
library/Controller/Singular.php
views/v3/partials/article.blade.php

- add new article layout
- add feature image
- add styling for article
- remove old layout

Article - New layout

---

assets/source/3.0/sass/footer.scss
assets/source/3.0/sass/generic.scss
assets/source/3.0/sass/main.scss
assets/source/3.0/sass/nav.scss
assets/source/3.0/sass/search.scss
library/Controller/Search.php
views/v3/partials/header.blade.php
views/v3/partials/search/search-form.blade.php

Add a button to show search field.
Move search field to a modal.
Minor changes to styling of search field and search-modal.

Navigation search

---

views/v3/page-two-column.blade.php
views/v3/sidebar-right.blade.php
views/v3/templates/archive.blade.php

Fixed the path to breadcrumb file.

path to breadcrumb

---

library/Api/Navigation.php
library/Helper/Navigation.php
views/v3/templates/single.blade.php

Get items to populate the sidebars
subcontainer with. Add route, add method to fetch
said items, add childItemsUrl to sidebar comp in single blade.

Get sidebar sub items

---

assets/source/3.0/sass/search.scss
views/v3/partials/hero.blade.php
views/v3/partials/search/hero-search-form.blade.php

- add layout for hero search
- add styling
- add relevant data
- add translate strings

Search in hero

---

library/Controller/Archive.php
library/Controller/FullWidth.php
library/Controller/Page.php
library/Controller/Search.php
library/Controller/Single.php
library/Controller/Singular.php
views/v3/full-width.blade.php
views/v3/templates/master.blade.php

Added boolean data variable to controllers. 
Changed master view. Added if statement to control sidebar with the boolean.

Full width view.

---

assets/source/3.0/sass/embed.scss

Making uploaded mp4 movies look good in container
Embed videos from Youtube & Vimeo looks great too. :-)

Renamed css class embed, added object-fit: cover

---

library/Helper/Navigation.php
library/Theme/General.php

Adds caching to heavy querys in the menu. Also adds a simple cache busting for these items.

Adds caching to meta querys in menu + cache busting

---

library/Theme/Enqueue.php

Enqueue styleguide css and js for the admin-panel to be able to preview blocks in the editor

Enque styleguide in admin

---

views/v3/partials/navigation/accessibility.blade.php

Added missing role to accessibility list items

fix: added missing role to accessibility list items

---

views/v3/partials/search/header-search-form.blade.php

Added aria-label to header search field.

Added aria-label for header search field

---

library/Oembed/YouTube.php

Added YouTube video title to embedded Iframes.

Added video title to embedded iframe

---

library/Theme/Sidebars.php

Switched placeholder string for "id" and "class" to make id unique and class general.
Not sure if this affects other functionality..

switched string for id and class to make id unique and class general

---

library/AcfFields/json/customizer-content-padder.json
library/AcfFields/php/customizer-content-padder.php
library/Bootstrap.php
library/Controller/BaseController.php
library/Controller/Singular.php
views/v3/templates/master.blade.php

Adds the ability to add space arount the main content columns according to design specifications.

3.0/feature/content padder

---

assets/source/3.0/sass/search.scss

Use new spacer module to achive padding.

Remove automatic margin on hero

---

library/Controller/BaseController.php
library/Helper/Post.php
library/Theme/CustomTemplates.php
views/v3/full-width.blade.php
views/v3/one-page.blade.php
views/v3/page-two-column.blade.php
views/v3/partials/loop.blade.php
views/v3/templates/single.blade.php

Removed duplicate templates (just includes single template)

Removes templates & implement gutenberg in onepage

---

library/Helper/Post.php
package-lock.json
package.json

Introduce standard paragraph, more & heading block. Fix read more bugs.

3.0/feature/paragraph

---

library/App.php
library/Upgrade.php

Simply create a new version number function in upgrade, and increase db version.

Functionality to make upgrade dabase functions

---

views/v3/partials/post/post-cards.blade.php

A bit scared I mess something unrelated up here :)
Footer was not shown but rendered in html.

CU-yjrpd0 add modifiers to show footer on card

---

library/Controller/Archive.php
library/Helper/Navigation.php
library/Helper/PostType.php
library/Theme/Navigation.php
package-lock.json
views/v3/partials/archive/archive-menu.blade.php
views/v3/templates/archive.blade.php

Create a menu location in top of all pages-

3.0/feature/archive menus

---

library/Controller/Archive.php

Use GMT format when displaying archive date

get gmt date time

---

library/App.php
library/Content/Images.php
library/Helper/Post.php
library/Theme/General.php

Moving normalizeImages to it's own class under Content

the_content only returns partial content 

---

library/Controller/Archive.php
library/Controller/BaseController.php
library/Template.php
readme.md

- add: view data filters with modifiers & deprecated in Template.php 
- remove: view data filters from BaseController
- remove: view data filters from ArchiveController
- update: documentation in readme

Refactor view data filters

---

library/Helper/Purpose.php

`change` renamed $postType to $type (posttype as type isn't technically required, terms or taxonomies could also be used)

`change` do not return false if type isn't an object (negates strings)

---

views/v3/templates/single.blade.php

Removing the one appearing at every post. 
Only showing the one in the bottom if post is not set to blogstyle

Changes signature

---

library/Controller/OnePage.php
library/Template.php
views/v3/one-page.blade.php

- Changed how loadController() instantiates controllers (custom page templates now requires a corresponding controller)
- Removed setting custom views via switchTemplate()

Refactoring loadController in Template.php (CU-865bkb62x)

---

library/Controller/Archive.php
library/Controller/Singular.php
library/Customizer/Sections/Archive.php
library/Helper/Post.php
library/Helper/ReadingTime.php
views/v3/partials/post/post-cards.blade.php
views/v3/partials/post/post-grid.blade.php

Also see https://github.com/helsingborg-stad/Modularity/pull/376, https://github.com/helsingborg-stad/component-library/pull/239

Feature/hämta in befintlig funktion för att visa lästid cu 865btwwv8

---

library/Customizer/Sections/Hero.php

* Customizer control Hero content background color.
* Customizer control Hero content contrasting color.
* Customizer control Hero content rounded corners.
* Customizer control Hero content shadows.
* Customizer control Hero content alignment.
* Customizer control Hero content text alignment.

Additional customizer controls for Hero

---

library/Controller/Archive.php
library/Controller/Singular.php
library/Helper/Archive.php
views/v3/one-page.blade.php
views/v3/partials/secondary.blade.php
views/v3/purpose-place.blade.php
views/v3/templates/single.blade.php

- Display the secondary query below the post content on page for term

Displaying secondary query on page for term 

---

library/Controller/BaseController.php

- Fallback to emblem on archives if no featured image is set

feature/Anvnd emblem p poster utan bild CU 865c063k9

---

assets/source/3.0/sass/archive.scss
views/v3/partials/secondary.blade.php

- Add anchorTag #filter to @pagination on singular
- Adding scroll margin

feature/Vid blddring i pagineringen scrolla direkt till filter CU 865c28dye

---

library/Customizer/Sections/Button.Test.php
library/Customizer/Sections/Button.php

Adds a customizer control that passes the selected value to all button components "shape" attribute.

Add button shape customizer control

---

library/Controller/Archive.php
library/Controller/Singular.php
library/Customizer/Applicators/ControllerVariables.php
library/Customizer/Sections/Archive.php
views/v3/partials/archive/archive-filters-secondary.blade.php
views/v3/partials/archive/archive-filters.blade.php

- Allow the "contains" keyword
- Display setting for each selected taxonomy
- Honor the settings when displaying the filters

feature/Typ av filtrering singleselect eller multiselect ska kunna stllas in CU 865c3yr8w

---

composer.lock
library/Controller/BaseController.php
views/v3/one-page.blade.php
views/v3/templates/single.blade.php

Some updates made while working on branch feature/Sk-bredvid-quicklinks-CU-865c1q21c on  https://github.com/helsingborg-stad/visit-custom-posttypes-taxonomies
- Ran composer update
- Prevent undefined notices

feature/Sk bredvid quicklinks CU 865c1q21c

---

library/Theme/Navigation.php
package-lock.json
views/v3/partials/navigation/tabs.blade.php

This also displays the tab menu as traditional buttons.

Change tab menu to be a real menu

---

library/Controller/Singular.php
library/Helper/Archive.php
views/v3/partials/article.blade.php

feat: Modify display of featured image on single post page 
refactor: Remove unused code for getting featured image data

Modify display of featured image on single post page

---

library/Controller/ArchivePurpose.php
library/Helper/Location.php
library/Helper/PurposePlace.php
views/v3/partials/secondary.blade.php

- feat: Add new method to create individual pins from posts 
- refact: Refactor createPinDataForPosts method to use new createPin method 
- refact: Refactor complementPlacePost method to use Location helper class for creating pins
- feat: Add js-data-url attribute to place map marker style: Add top margin to openstreetmap post group

feature/Pusha nya states i kartan till urlen CU 865c8rh2h 2

---

library/Helper/General.php
library/Language.php

feat: Add filters to exclude content from Google Translate
feat: Add checkbox on post edit screen for exclude_from_google_translate (postmeta)

feat: Add filters to exclude content from Google Translate

---

library/Theme/Navigation.php

Depth was set to 0 in some cases

menu ids fix

---

library/Controller/Archive.php
library/Helper/Archive.php
views/v3/partials/archive/archive-filters.blade.php

- (feat) Adding filter "`Municipio/Archive/getTaxonomyFilters/taxonomies`" to be able to filter taxonomies available for the archive filters

feature/Kategorifilter p event frsvinner nr en eller flera kategorier r valt CU 865cnw3d5

---

library/Template.php

Wrong template and controller when one-page is the first item in an archive

Fix: Wrong template and controller

---

library/Api/Pdf/PdfHelper.php
library/Api/Pdf/PdfIdEndpoint.php
library/Helper/S3.php

This PR enhances the font conversion process by integrating seamless support for Amazon S3 storage. The convertWOFFToTTF function has been updated to provide improved efficiency and reliability when handling font files stored on S3.
The S3 helper class has been introduces with additional functionalities for handling S3 operations. The key features include:
Object Existence Check: The objectExistsOnS3 method now returns the restored S3 key if the object exists on S3. This can be helpful in obtaining the actual filename when checking for the existence of an object.
Upload and Download Operations: The uploadToS3 and downloadFromS3 methods now perform S3 key sanitization before operation, ensuring consistent and accurate S3 key handling.
Path Check: The isS3Path method allows you to check if …

Feature/s3 file management & font implementation

---

library/Controller/ContentType/School/SchoolDataPreparer.php
views/v3/content-type-school.blade.php

`feat`: Add sanitized version of accordion__item heading as id on each accordion__item

Accordion anchor links on school pages #CU-8693cbytp

---

composer.json
composer.lock

This is solely attributable to the vendor's neglect in maintenance.

feat: Replace Kirki with our custom version.

---

library/App.php
library/ImageConvert/Config/ImageConvertConfig.php
library/ImageConvert/Config/ImageConvertConfigInterface.php
library/ImageConvert/ImageConvertFilter.php
library/ImageConvert/ImageConvertFilter.test.php
library/ImageConvert/IntermidiateImageHandler.php
library/ImageConvert/NormalizeImageSize.php
library/ImageConvert/ResolveToWpImageContract.php
library/ImageConvert/Resolvers/MissingSize/ResolveMissingImageSize.php

The short circuits the image resize.

feat: image handle of really large image should not be possible.

---

library/Content/CustomPostType.php

Adds filter to have possibility to change CustomPostType labels.

feat: add filter to change CustomPostType labels

---

assets/source/3.0/sass/navigation/_user.scss
library/Customizer/Sections/Header/LoginLogout.php
views/v3/partials/header/user/login.blade.php
views/v3/partials/header/user/user.blade.php

fix: remove color options on logged out

---

assets/source/3.0/sass/main.scss
assets/source/3.0/sass/search-modal.scss
assets/source/3.0/sass/search.scss
views/v3/partials/search/search-modal.blade.php

This pull request introduces a new search modal feature and refactors existing search form styles. The changes include adding a new SCSS file for the search modal, updating the main SCSS file to include this new file, and modifying the Blade template for the search modal.
* [`assets/source/3.0/sass/search-modal.scss`](diffhunk://#diff-362bd1c636e5d24b77fd7dca56f33f00f447f85772a6b04875d629299211de83R1-R99): Added new SCSS file to define styles for the search modal, including breakpoints and grid layout for the form elements.
* [`views/v3/partials/search/search-modal.blade.php`](diffhunk://#diff-f260ae2a1215804e89c88b6445400d2751c125774568d1370e632144e8bba4bfL3-R3): Updated the Blade template to use new class names for the search modal elements, ensuring they align with the new styles …

fix: stack modal search form in modal.

---

library/Theme/Enqueue.php

This unfortunately caused some issues with rendering of some components in edge-cases.

fix: revert block-library dequeue.

---

library/Helper/Term/Term.test.php
library/PostObject/Date/ArchiveDateFormatResolver.test.php
library/PostObject/Date/ArchiveDateSourceResolver.test.php
library/PostObject/Date/CachedArchiveDateFormatResolver.test.php
library/PostObject/Date/CachedArchiveDateSourceResolver.test.php
library/PostObject/Date/TimestampResolver.test.php
library/StickyPost/Helper/GetStickyOption.test.php

- Increase speed of test suite by removing unnecessary test separate processing.

test: remove unnecessary test separate processing

---

library/Theme/General.php

The force_balance_tags is a work of art. I have not seen anything worse in a long time.

fix: removes ineffective force_balance_tags function call.

---

library/Controller/BaseController.php
library/Customizer/Sections/Menu/Breadcrumbs.php

Goes together with https://github.com/helsingborg-stad/component-library/pull/555

feat: additional settings for breadcrumbs component

---

assets/source/3.0/sass/401.scss
assets/source/3.0/sass/403.scss
assets/source/3.0/sass/404.scss
library/Controller/E401.php
library/Controller/E403.php
library/Controller/E404.php
library/Customizer/PanelsRegistry.php
library/Customizer/Sections/ErrorPages.php
views/v3/partials/401/default.blade.php
views/v3/partials/403/default.blade.php
views/v3/partials/404/default.blade.php

- New Customizer section for error pages
- Possibility to customise 401, 403 and 404 pages
- Customisation includes:
- Heading
- Subheading
- Image
- What action buttons to display
- Whether or not to display an error code backdrop

feat: customisation for error pages
