- library/Comment/HoneyPot.php
This is completely untested but I think it just fixes a typo. It will however change the value of `$this->field_content` since `NONCE_SALT+NONCE_KEY` is 0. I think that you want to concatenate those strings so that is what I'm doing instead.
It also fixes an error in PHP 7.1 since 7.1 complains when you use `.` with strings.
> Fix incorrect string concatenation i honeypot

- library/Helper/NavigationTree.php
There is a huge performance regression on my local site when performing a search with no results. From 10s to 1.5s.
I'm not sure the if clause introduced here is the best place to deal with it, but works for me...
The underlying issue is that getCurrentPage(),  returns Null if there are no results, but the first result if there are results (`get_queried_object()`). See https://github.com/helsingborg-stad/Municipio/blob/master/library/Helper/NavigationTree.php#L144
When walk() then gets an array with Null as the only item it goes out of control it seems.
> Fix performance regression in menu if no current page

- acf-exports/acf-theme-options-mobile-navigation.json
- library/Helper/Navigation.php
We plan to not use the mobile menu at all. This adds a setting to disable it. This is mainly for performance reasons since even if we don't output it in our theme it's still being created. And the menu code is as you know quite heavy.
Since it's enabled by default and we do a strict check (if the option is `null` it will be rendered) it means it's backward compatible.
> Add theme option to disable mobile menu

- library/Content/PostFilters.php
This follows the same approach as in https://github.com/helsingborg-stad/Modularity/pull/16.
Again, I'm not sure if meta_query that is removed in this commit did something else than sort.
> Fix sort by meta field on archive pages

- library/Search/General.php
Fixes warning i Google search where $post is `null`.
> Fix warning in Google search

- assets/dist/js/mce-picons.php
Pricons aren't working in tinymce because they cant find `http://hbgprime.dev/*`.
> Update styleguide pricons url

- readme.md
Adds a very short note regarding the dependency on ACF PRO to the README.
> Document dependency on ACF PRO

- library/Helper/Styleguide.php
Just a suggestion, not sure if this is actually better. The hard-coded URI might not be necessary anymore since `MUNICIPIO_STYLEGUIDE_URI` could be used instead.
> Suggestion to remove the hard-coded styleguide development URI

- views/partials/footer.blade.php
Modules placed in the "Bottom sidebar (full-width)" are currently placed directly under the body-tag. Wrapping this section makes it easier to control the layout of its content.
> Add wrapper for bottom sidebar in footer partial

- bem-views/404.blade.php
Fixes a logged error:
```
[Tue Apr 24 13:58:30 2018] PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function e()
0 passed in wp-content/uploads/cache/blade-cache/dbfa6c3140a9f494b56948f15ea9fd5e1fb63e85.php on line 10 and at least 1 expected in vendor/illuminate/support/helpers.php:574
Stack trace:
#0 wp-content/uploads/cache/blade-cache/dbfa6c3140a9f494b56948f15ea9fd5e1fb63e85.php(10): e()
#1 vendor/illuminate/view/Engines/PhpEngine.php(43): include('...')
#2 vendor/illuminate/view/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('...' Array)
#3 vendor/illuminate/view/View.php(137): Illuminate\View\Engines\CompilerEngine->get('...' Array)
#4 vendor/illuminate/view/View.php(120):  in …
```
> Fix warning for call to Illuminate Support

- composer.json
Using symfony/debug 3 prevents composer from installing later versions of the illuminate dependencies.
(See https://packagist.org/packages/illuminate/view#v5.8.0)
> Update symfony/debug to version 4

- library/Theme/Sidebars.php
By removing the before-widget and after-widget markup configuration
from registered sidebars we can now render multiple modules
in an area. We might want to look into cleaning up or replacing this markup
in a future commit.
> Remove before and after-widget markup

- library/Helper/Navigation.php
If it's an archive or it's decendant then add the archive page to the
array containing breadcrumbs, if it's a page for post type, then ignore
it when looping through ancestors, since we added in the step before.
> Fix breadcrumb not showing complete path

- library/AcfFields/json/block-classic-editor.json
- library/AcfFields/php/block-classic-editor.php
- library/Admin/Gutenberg/Blocks/BlockManager.php
- library/Admin/Gutenberg/Blocks/views/button.blade.php
- library/Admin/Gutenberg/Blocks/views/classic.blade.php
- library/Admin/Gutenberg/Blocks/views/default.blade.php
- library/App.php
- library/Bootstrap.php
Add a new block that utilizes wysiwyg editor field to
replace the classic editor because a known issue with creating links.
Repurpose the button class. Making it able to register and render any
block created within Municipio.
Add a notice that is shown when required fields are not filled in.
> Classic editor replacement

- library/Template.php
Move the init of blade to template_redirect action so that we can access wp functions when overriding templates
> CU-mn87c5 initiate blade engine in a later stage to get more wp functions when overriding templates

- assets/source/3.0/sass/article.scss
Not sure if this is the "correct" way to do it. But I set all the child items of an article to have the same "max-width" as the maximum width of "content" in municipio.
> Replaced ch with px and setting all article children to same width

- views/v3/partials/comments.blade.php
Reverted to not using WP date format settings for comments. Since strotime is used it should work with standard date/time formats, but helsingborg.se had added a comma, which broke the time calculation. Moreover it superflous, since it is here only used by the date component for computing elapsed time.
> Date format in time since comment

- library/Controller/BaseController.php
- library/Helper/ElementAttribute.php
- views/v3/partials/loop.blade.php
- views/v3/partials/post/post-compressed.blade.php
- views/v3/partials/signature.blade.php
Fixes undefined values and other stuff that trigger PHP errors.
Fixes:
- Check for signature object before using it (signature.blade.php)
- Check for $post->archiveDate property before using it (post-compressed.blade.php)
- PostType name is not always defined in eg. 404 pages (BaseController.php)
- Set empty string when the targeted menu is not configured (BaseController.php)
- Fix typo (Helper/ElementAttribute.php)
> 3.0/fix/php errors

- library/Customizer/Applicators/Css.php
Make any font value entered in PX to resolve to a em value. Only applies if the following rules apply: 
- CSS Applicator is used
- Unit is in PX 
- Key contains 'font'
> Normalize px to em fonts

- assets/source/3.0/js/admin/designShare.js
Using startsWith instead of includes if a key contains something like posts_archive_bg_color
> Removes the archive related settings from error msg

- library/Customizer.php
Fixes issue with missing post types under the Archives panel in the customizer.
> Await post types before registering customizer panels

- assets/source/3.0/js/admin/widgetsAreaHider.js
- library/Customizer/Sections/Archive.php
- library/Theme/Enqueue.Test.php
- library/Theme/Enqueue.php
* Incorrectly enqueued scripts caused Error "wp is not defined".
* When using Kirki active_callback and depending on a Kirki multi select field the default value of the dependency field cannot be an empty string. Solved by using an empty array.
* Handle possibly missing element throwing in widgetAreaHider.
> Fix: Customizer not saving

- library/Admin/General.php
Fixes unhandled warning when passing strings to implodes 2nd parameter.
> fix: invalid parameters passed to implode

- library/Content/CustomPostTypesFromApi.php
> fix: CustomPostTypesFromApi::modifyBreadCrumbItems throws when $pageData is null

- library/Helper/Post.php
This fix, intends to improve performance by blocking and returning already knows results from runtime cache whenever a intentical request is made towards preparePostObject functions.
> fix: implement the runtime cache on preparePost functions.

- library/Helper/Post.php
- tests/phpunit/tests/Helper/Post.php
When multiple posts have the same ID they are overwritten in the preparePostObject cache. To avoid this conflict the post_date is also used to make the cache key unique.
> fix: Posts with same ID are overwritten in preparePostObjectCache

- library/Upgrade.php
This PR introduces a change to remove all post metadata entries in the WordPress database where the meta_key matches _oembed%. The purpose of this change is to clean up unnecessary or outdated oEmbed cache data from the wp_postmeta table, this is due to a change in the icons rendering causing icons not to appear.
> fix: clear cache of oembeds.

- library/Helper/Archive.php
Fixed the issue where the archive helper camel cases post_type to Post_type, different to the customizer that camel cases it to PostType. Without this fix we get a mismatch when the archive tries to fetch the customizer data.
> fix: archive helper camel case

- library/Template.php
For instance on search or an archive
> Don't try to get page template if no object was queried

- library/Customizer/Applicators/ApplicatorCache.php
This enshures that a fallback cache key, dosen't regenerate if saving takes a long time.
> fix: normalize now

- library/Api/Pdf/PdfArchiveEndpoint.php
This pull request includes several changes to the `PdfArchiveEndpoint` class in the `library/Api/Pdf` directory. The main updates involve adding query parameter validation, modifying method signatures, and updating the date query logic.
* [`library/Api/Pdf/PdfArchiveEndpoint.php`](diffhunk://#diff-fba111877bb66fb5fe3442234d7d1b2d60e64c33c04f892bb22780f60a704fe4L33-R43): Added validation for `after` and `before` query parameters in the `handleRegisterRestRoute` method.
* [`library/Api/Pdf/PdfArchiveEndpoint.php`](diffhunk://#diff-fba111877bb66fb5fe3442234d7d1b2d60e64c33c04f892bb22780f60a704fe4L91-R101): Updated the `handleRequest` method to pass query parameters to the `getPostsFromArchiveQuery` method.
* [`library/Api/Pdf/PdfArchiveEndpoint.php`](diffhunk://#diff-fba111877bb66fb5fe3442234d …
> feat(api/pdf): enhance PdfArchiveEndpoint with date filtering arguments

- library/AcfFields/json/options-login-logout.json
- library/AcfFields/php/options-login-logout.php
- library/Admin/Integrations/MiniOrange/Config/MiniOrangeConfig.php
- library/Admin/Integrations/MiniOrange/Config/MiniOrangeConfigInterface.php
- library/Admin/Integrations/MiniOrange/RequireSsoLogin.php
- library/Admin/Login/DoNotHaltLogoutWhenNonceIsMissing.php
- library/Admin/Login/EnqueueLoginScreenStyles.php
- library/Admin/Login/LogUserLoginTime.php
- library/Admin/Login/RegisterLoginLogoutOptionsPage.php
- library/Admin/Login/SetLoginScreenLogotypeData.php
- library/App.php
- library/Bootstrap.php
- library/Controller/BaseController.php
This pull request includes significant changes to the login and logout functionality, including the integration of Single Sign-On (SSO) with MiniOrange, as well as several enhancements to the login process. The changes introduce new classes, update existing ones, and rename some files for better clarity.
* Added `MiniOrangeConfig` and `MiniOrangeConfigInterface` to manage MiniOrange SSO settings and check if SSO login is required. (`library/Admin/Integrations/MiniOrange/Config/MiniOrangeConfig.php` [[1]](diffhunk://#diff-9380cd291f508096a63a97059ccf4291a6872f90ca5035204894262363bc55fdR1-R28) `library/Admin/Integrations/MiniOrange/Config/MiniOrangeConfigInterface.php` [[2]](diffhunk://#diff-a55af3629399f8e9e496223c19ed47ebc2a5faf978c115a1bfc95e9d72a77f71R1-R9)
* Implemented …
> feat: force sso login

- library/AcfFields/json/options-login-redirect.json
- library/AcfFields/php/options-login-redirect.php
- library/App.php
- library/Bootstrap.php
- library/Controller/BaseController.php
- library/Integrations/BrokenLinks/Config/BrokenLinksConfig.php
- library/Integrations/BrokenLinks/Config/BrokenLinksConfigInterface.php
- library/Integrations/BrokenLinks/RedirectToLoginWhenInternalContext.php
This pull request introduces a new feature to handle broken links by redirecting users to the login page when an internal context is detected. The changes include updates to JSON and PHP configuration files, modifications to existing classes, and the addition of new classes for handling the broken links integration.
* **Configuration Changes:**
* Added a new JSON configuration file `options-login-redirect.json` to define the "Autologin" field for the broken links feature.
* Updated the PHP configuration file `options-login-redirect.php` to register the new "Autologin" field with Advanced Custom Fields (ACF).
* Modified `library/Bootstrap.php` to include the new configuration group `options-login-redirect`.
* **Codebase Enhancements:**
* Updated `library/App.php` to set up the broken links …
> feat: autologin

- composer.json
- library/Customizer.php
- library/Customizer/FontUploads/FontUploads.php
This pull request introduces a new implementation for handling custom font uploads and integrates it into the customizer. The most important changes include the removal of the old font upload module, the addition of a new `FontUploads` class, and updates to the `composer.json` file to reflect these changes.
* **Removal of old font upload module**:
- Removed the `ouun/kirki-module-fonts_upload` dependency from `composer.json`.
- Removed the old font upload initialization code from the `init` method in `library/Customizer.php`.
* **Addition of new `FontUploads` class**:
- Added a new `FontUploads` class in `library/Customizer/FontUploads/FontUploads.php` to handle custom font uploads, including methods for adding hooks, getting uploaded fonts, adding font MIME types, adding uploaded fonts …
> feat: custom font loader

- library/App.php
- library/UserGroup/Config/UserGroupConfig.php
- library/UserGroup/Config/UserGroupConfig.test.php
- library/UserGroup/CreateUserGroupTaxonomy.php
- library/UserGroup/CreateUserGroupTaxonomy.test.php
This pull request includes several changes to the `library` directory, primarily focusing on enhancing the `UserGroupConfig` class and its integration with the `wpService`. The most important changes involve modifying the constructor to accept a `wpService` parameter, updating related methods to use this service, and adding new functionality and tests to handle multisite configurations.
* [`library/UserGroup/Config/UserGroupConfig.php`](diffhunk://#diff-39ab713b35712881dbf9c2c144f4ae21a617e10eb2cc12130f469adec16fb9f2L13-R18): Updated the constructor to accept a `wpService` parameter, added a new method `getStoreUserGroupTaxonomyOnMainBlog()` to determine if the user group taxonomy should be stored on the main blog. [[1]](diffhunk://#diff-39ab713b35712881dbf9c2c144f4ae21a617e10eb2cc12130f46 …
> feat: only allow UserGroup taxonomy on main site if multisite

- library/Admin/Login/RedirectUserToGroupUrlIfIsPreferred.php
- library/Helper/User/Contracts/GetRedirectToGroupUrl.php
- library/Helper/User/User.php
- library/Integrations/MiniOrange/AllowRedirectAfterSsoLogin.php
- library/Integrations/MiniOrange/AllowRedirectAfterSsoLogin.test.php
- library/UserGroup/RedirectToUserGroupUrlAfterSsoLogin.php
- library/UserGroup/RedirectToUserGroupUrlAfterSsoLogin.test.php
This pull request includes changes to improve the handling of redirects after SSO login by adding support for user-specific redirects and enhancing type safety. The most important changes include updating method signatures to accept additional parameters and modifying filter and action hooks to pass these parameters.
Enhancements to redirect handling:
* [`library/Integrations/MiniOrange/AllowRedirectAfterSsoLogin.php`](diffhunk://#diff-ab40ed2c511af58c876f70b01426bc022e0bc893af8e283ec4756ef9c56d5456L30-R46): Updated the `allowRedirectAfterSsoLogin` method to accept additional parameters and modified the `addAction` call to pass these parameters. Added suppression annotations for unused variables.
* [`library/UserGroup/RedirectToUserGroupUrlAfterSsoLogin.php`](diffhunk://#diff-95a48fd074d11 …
> fix: send user id trough miniorange get redirect url

- library/App.php
- library/PostDecorators/ApplySeoRedirect.php
This pull request introduces a new SEO redirect feature to the `library` module. The main changes involve adding a new post decorator class and integrating it into the existing post decoration process.
* [`library/App.php`](diffhunk://#diff-f866e0aad6c55f4178f285d128ff5bb496ce75bdc2106be7aafbaed7b5cc1e1eR183-R185): Added the `ApplySeoRedirect` post decorator to the post decoration chain in the `__construct` method.
* [`library/PostDecorators/ApplySeoRedirect.php`](diffhunk://#diff-3e60727d5021908ad8ecae0eeda80155e23aecafb9270f6fbf55f4e8aa61aab6R1-R40): Created the `ApplySeoRedirect` class, which implements the `PostDecorator` interface. This class replaces the permalink of a post with a redirect URL if one is set.
> feat: replace permalinks to posts that are redirected.

- library/PostObject/Decorators/BackwardsCompatiblePostObject.php
- library/PostObject/Decorators/BackwardsCompatiblePostObject.test.php
Allow setting other class properties than `permalink` on PostObject when using BackwardsCompatiblePostObject.
> fix: allow setting props on PostObject

- library/UserGroup/AddSelectUserGroupForPrivatePost.php
This pull request includes several changes to the `library/UserGroup/AddSelectUserGroupForPrivatePost.php` file to enhance security and functionality. The most important changes involve adding nonce verification to improve security and updating the constructor to include new service dependencies.
Security improvements:
* Added `WpService\Contracts\CheckAdminReferer` and `WpService\Contracts\WpNonceField` to handle nonce verification and field creation.
* Introduced constants `NONCE_ACTION` and `NONCE_NAME` for nonce handling in the `AddSelectUserGroupForPrivatePost` class.
* Implemented nonce verification in the `saveUserVisibilitySelect` method to ensure requests are valid.
* Added a nonce field in the `renderPrivateVisibilityList` method to include nonce data in forms.
Constructor …
> feat: add nonce verification for user group visibility updates

- library/StickyPost/AddStickyCheckboxForPost.php
- library/UserGroup/AddSelectUserGroupForPrivatePost.php
This pull request includes changes to the `addHooks` method in two files to ensure that the `saveStickyCheckboxValue` and `saveUserVisibilitySelect` actions are triggered correctly. The changes involve replacing the `save_post` action with the `edit_post` action.
Changes to action hooks:
* [`library/StickyPost/AddStickyCheckboxForPost.php`](diffhunk://#diff-ad11d4b84083e449809634a875cad2fc711dc1c3095121df8e620c0901435d7bL49-R49): Changed the action hook from `save_post` to `edit_post` for the `saveStickyCheckboxValue` method to ensure it is triggered during the edit post process.
* [`library/UserGroup/AddSelectUserGroupForPrivatePost.php`](diffhunk://#diff-09513c2dbc86f5664644c15367ca4de970372bcecaf3d92734bca3d7a53b1fb6L54-R54): Changed the action hook from `save_post` to `edit_post` for …
> fix: change action to edit_post for sticky checkbox and visibility select

- library/StickyPost/AddStickyCheckboxForPost.php
- library/UserGroup/AddSelectUserGroupForPrivatePost.php
This pull request involves several changes to replace the `CheckAdminReferer` contract with the `WpVerifyNonce` contract across different files. The changes ensure a more consistent and secure way of verifying nonces within the codebase.
* Replaced `CheckAdminReferer` with `WpVerifyNonce` in the list of used contracts.
* Updated the constructor to use `WpVerifyNonce` instead of `CheckAdminReferer` in the `$wpService` parameter.
* Modified the `saveStickyCheckboxValue` method to use `wpVerifyNonce` instead of `checkAdminReferer`.
* Replaced `CheckAdminReferer` with `WpVerifyNonce` in the list of used contracts.
* Updated the constructor to use `WpVerifyNonce` instead of `CheckAdminReferer` in the `$wpService` parameter.
* Modified the `saveUserVisibilitySelect` method to use …
> fix: do not check admin referer, verify nonce.

- library/Controller/Singular.php
This pull request includes changes to the `library/Controller/Singular.php` file to improve the handling of post data in the `getSignature` method. The most important changes involve passing the `post` object as a parameter to the `getSignature` method and updating the method to use this parameter for retrieving post-related information.
* Modified the `init` method to pass the `post` object to the `getSignature` method.
* Updated the `getSignature` method to accept the `post` object as a parameter and use it for retrieving author information and post dates.
> fix: send timestamps to published/updated in signature.

- library/Controller/Archive.php
This pull request includes changes to the `library/Controller/Archive.php` file to enhance the date formatting for posts and taxonomy terms. The most important changes include modifying the date format in the `getListItems` and `prepareTaxonomyColumns` functions.
Improvements to date formatting:
* [`library/Controller/Archive.php`](diffhunk://#diff-c406e1b5d78eacda466d38f1df2f163898d4bf85db6b4020b9c88b8c36732bbbL630-R630): Updated the `getListItems` function to use `wp_date` with the WordPress date format option for `post_date`.
* [`library/Controller/Archive.php`](diffhunk://#diff-c406e1b5d78eacda466d38f1df2f163898d4bf85db6b4020b9c88b8c36732bbbL660-R665): Modified the `prepareTaxonomyColumns` function to format term names as dates when possible using `wp_date` and the WordPress date …
> fix: resolves issues with archive lists and dates

- library/Template.php
This pull request includes a change to the `public function renderView($view, $data = array())` method in the `library/Template.php` file. The change modifies the HTML tidy functionality to improve readability and fix validation issues. This feature should be enabled in order to improve html output that are not adjustable by code; for example <br/> tags origin from tinymce editor, and other. 
Improvements to HTML tidy functionality:
* [`library/Template.php`](diffhunk://#diff-7a810c83f9eec229237054e7bf7bd4b18443a6e6246f1a089a3e0d02889cbc3dL298-R306): Updated the condition to enable HTML tidy only if the `DISABLE_HTML_TIDY` constant is not defined or set to false. Additionally, added the `doctype` option set to 'html5' to the tidy configuration.
You may use DISABLE_HTML_TIDY set to TRUE in …
> feat: enables tidy html that cleans html output to comply with current standards

- library/Content/Images.php
This pull request focuses on enhancing the URL sanitization process in the `library/Content/Images.php` file. The most important change involves updating the `sanitizeRequestUrl` function to include the port number in the URL reconstruction if it is not the default HTTP or HTTPS port.
Improvements to URL sanitization:
* [`library/Content/Images.php`](diffhunk://#diff-4d0da5f359168108b5b8307b265f8f3995c1a24e39ed8561730a18d79979ca64R252): Modified the `sanitizeRequestUrl` function to append the port number to the URL if it is not 80 or 443. This ensures that non-standard port numbers are preserved in the sanitized URL.
> fix: include port in sanitized URL if not default

- library/Actions/Admin/PostPageEditAction.php
- library/Actions/Admin/PostPageEditAction.test.php
- library/App.php
- readme.md
This pull request introduces a new feature to handle actions when a post page is edited in the admin area. It includes the implementation of the `PostPageEditAction` class, corresponding tests, and updates to the `App` class and documentation.
New feature implementation:
* [`library/Actions/Admin/PostPageEditAction.php`](diffhunk://#diff-a684c4d22f59e0706182e26450ce6de67ced1fcd2ebe851136265da09b733bcaR1-R58): Added the `PostPageEditAction` class to handle the action when a post page is edited in the admin area. This class hooks into the `current_screen` action and triggers a custom action with the post ID and post type.
Testing:
* [`library/Actions/Admin/PostPageEditAction.test.php`](diffhunk://#diff-ab21751643fcb35bf30ecf7a9834835c0e8350082936904d41eb2d340b82b0b2R1-R102): Added unit …
> feat: add PostPageEditAction to handle post editing actions

- library/Customizer/Applicators/ApplicatorCache.php
- library/Customizer/Sections/Menu/Vertical.php
- views/v3/partials/navigation/mobile.blade.php
- views/v3/partials/navigation/sidebar.blade.php
This pull request includes several changes to improve caching and navigation context handling in the codebase. The most important changes focus on enhancing the caching mechanism and updating the context for navigation components.
* [`library/Customizer/Applicators/ApplicatorCache.php`](diffhunk://#diff-25a54abb299fdef3c48d6300f245b94ded039f63a0c6ee35f25d2d96901eb791L37-R42): Updated the `addHooks` method to create and apply cache on REST requests and simplified the `isFrontend` method by removing unnecessary conditions. [[1]](diffhunk://#diff-25a54abb299fdef3c48d6300f245b94ded039f63a0c6ee35f25d2d96901eb791L37-R42) [[2]](diffhunk://#diff-25a54abb299fdef3c48d6300f245b94ded039f63a0c6ee35f25d2d96901eb791L187-R190)
* [`views/v3/partials/navigation/mobile.blade.php`](diffhunk://#diff-d584a9019a …
> fix: resolve issue with applicators not running in rest response

- library/SchemaData/SchemaPropertiesForm/StoreFormFieldValues/StoreFormFieldValues.php
Not allowing multiple types for save_post may cause fatal errors. This fix provides neccesary typing for these cases, and instead returns if not a number.
> fix: allow menu pages etc. to be saved.

- library/ImageConvert/IntermidiateImageHandler.php
This change provides a temporary workaround for environments where processing PNG images with alpha transparency causes errors — typically due to issues with the Imagick extension.
•	Instead of resolving the underlying cause, this PR avoids the issue by prioritizing the GD image editor for PNG files.
•	This helps prevent fatal errors when Imagick encounters problematic transparency data in PNGs.
•	Note: This is not a complete fix — it sidesteps the problem by using a more robust fallback editor (GD), which is known to handle these cases more gracefully.
Further investigation is needed to fully resolve compatibility with Imagick and alpha-channel PNGs.
> fix: sidestep image downsize alpha png errors

- assets/source/3.0/sass/navigation/_collapsible-search.scss
Restore missing styles for Collapsible Search
This pull request reintroduces critical styling that was unintentionally removed in previous changes:
The original implementation of the Collapsible Search feature was merged without some of the necessary styles for proper layout and appearance.
On February 4, additional styling—particularly important for the mobile view—was removed in a commit by @NiclasNorin, which further affected the visual integrity of the component.
What this fixes
The following visual bugs have been resolved:
Broken mobile layout:
Broken desktop layout:
✅ Fixed layout (after this PR):
> ⚠️ Note: Please disregard the colors in the screenshots — they reflect my local development environment and may differ from the default theme.
This PR aims to restore the intended …
> Fix for the feature "Collapsible search"

- library/SchemaData/ExternalContent/SyncHandler/FilterBeforeSync/ConvertImagePropsToImageObjects.php
- library/SchemaData/ExternalContent/SyncHandler/FilterBeforeSync/ConvertImagePropsToImageObjectsTest.php
- library/SchemaData/ExternalContent/SyncHandler/SyncHandler.php
This pull request introduces a new filter for the external content sync process to automatically convert image property values to `ImageObject` instances, ensuring consistent schema handling of image data from external sources. Comprehensive unit tests are included to verify correct behavior for root, nested, and array image properties, as well as edge cases.
* Added `ConvertImagePropsToImageObjects` filter (`library/SchemaData/ExternalContent/SyncHandler/FilterBeforeSync/ConvertImagePropsToImageObjects.php`) that recursively converts any property (root or nested) accepting `ImageObject` or `ImageObject[]` types to proper `ImageObject` instances, handling both single URLs and arrays of URLs.
* Registered the new filter in the sync handler so it runs before syncing external content …
> fix(ExternalContent): normalize image properties
